services:
  - type: web
    name: finautojobs-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://finautojobs-backend.on.render.com/api
    repo: https://github.com/BHARGAV15008/FinAutojobs-A-Job-Portal.git
    branch: main
    rootDir: frontend
